### PR TITLE
upgrade plugin itself to grails 3.2.4 and cleanup

### PR DESCRIPTION
**Pull request by snimavat**

### CODE REVIEW

**Comment by iamthechad** [comment]
Thanks for this submission. Please take a look at the [contribution guidelines](https://github.com/iamthechad/grails3-recaptcha/blob/v3.x/CONTRIBUTING.md).

This project prefers to have issues opened first, even for PRs, in order to facilitate discussion.

In particular, I'd like to know: what problems does this PR solve? 

This PR also seems to be targeting several different things - plugin upgrade, Travis CI config, "cleanup". Ideally, these separate changes should be handled in separate PRs.

**Comment by snimavat** [comment]
@iamthechad the goal was to upgrade to latest grails, clean up build... i also cleanup few things with travis, but no behavior is changed.

**Comment by iamthechad** [comment]
Is there a need to upgrade to the latest Grails? Does this solve a problem?

Is there a need to modify the Travis configuration? Does this solve a problem?

There were also a lot of changes to code to change from dynamic typing to static typing. Does this solve a problem?

**Comment by snimavat** [comment]
Upgrading to latest grails helps - yes
Travis, no, this was just for cleaning up and enabling gradle caches
Compile static - thts just cleanup, i think static compilation is preffered.. that doesnt change any behavior though and all tests pass...

**Comment by iamthechad** [comment]
Then what is needed is 1 PR for just the Grails upgrade that references the original issue (#17). For what it's worth, I was completely unable to reproduce the issue noted in #17, so more information is needed before I'll be convinced that the upgrade is needed.

A new issue for the Travis changes can also be opened, since this changes are separate.

A new issue can also be opened for the dynamic to static type changes, and the merits of such a change can be discussed there.

I am not comfortable merging this PR with the number and type of changes.

**Comment by snimavat** [comment]
@iamthechad sure, will give seperate PRs for each and will have a ticket for them..
The code which fails to compile with current version is here https://github.com/snimavat/recaptcha-spring-security/tree/grails3 just in case if you are curious to try it.

**Pull request closed without merging**
