### PR TITLE
Update application.yml

### PR DESCRIPTION
**Pull request by Schlogen**
Remove production datasource to prevent adding config to a users production datasource

### CODE REVIEW

**Comment by iamthechad** [comment]
Two notes:

* I don't see that `application.yml` is published with the plugin. I just checked the `3.0.0` binaries and this file is only packed with the sources jar.

* If this truly is a problem, please submit a PR against the current target branch per https://github.com/iamthechad/grails3-recaptcha#contributing

**Comment by Schlogen** [comment]
Per that link: "Be sure to submit pull requests against the current "target branch". This will ensure that changes are applied to the correct version."

What is the "target branch"? It is possible it's not included in the jar. I searched for the dbCreate text throughout all sources and it showed the setting in this plugin. Even so, why not remove it? Is there a compelling reason to leave it?

**Comment by iamthechad** [comment]
The target branch is called out just below the Table of Contents and again in the Contributing section:
Target Branch

**Comment by Schlogen** [comment]
Created a new PR to the target branch

**Pull request closed without merging**
