### PR TITLE
Add null safe check for getting response param

### PR DESCRIPTION
**Pull request by Schlogen**

### CODE REVIEW

**Comment by Schlogen** [comment]
If you would like to update it, go ahead, otherwise just close the PR as these minute details on a 1 character change PR are not worth the effort

**Comment by iamthechad** [comment]
These minute details are how I maintain the quality of the software. It's not just a one-character change because the unit test is just as important, and it's just as essential that it be correct.

If you're not comfortable with this, I'm sorry. Open an issue next time if you'd rather not have to deal with the details of changing code.

**Comment by Schlogen** [comment]
I realize you are being difficult because you get some satisfaction from it. Given that you changed it in your 2.x codebase a half hour ago and could have simply changed the test to your liking here.

**Comment by iamthechad** [comment]
You can believe whatever you want. I have an expectation that submissions are complete and correct before I merge them. If that makes me difficult, then so be it.

What I'm asking is no different than what I've been asked to do as a contributor to other OSS projects. (It's actually easier. I could have asked you to squash your commits, use a very specific comment format, etc.)

**Pull request closed without merging**
